Repository kowainik/stan, pull requests merged in 2020-04, with the labels that each got.

#10 [#3] Clean up repo
  .github/CODEOWNERS
  .github/workflows/ci.yml
  .gitignore
  .travis.yml
  CHANGELOG.md
  README.md
  cabal.project
  src/Stan.hs
  src/Stan/Analysis.hs
  src/Stan/Partial.hs
  src/Stan/Warning.hs
  stan.cabal
  test/Spec.hs
Labels: refactoring

#11 [#5] Create basic command line interface
  .stylish-haskell.yaml
  app/Main.hs
  src/Stan.hs
  src/Stan/Cli.hs
  stan.cabal
Labels: CLI

#12 [#9] Count the number of analyzed modules
  src/Stan/Analysis.hs
  stan.cabal
Labels: report :notebook:

#15 [#4] Read hie files of the target project
  README.md
  src/Stan.hs
  src/Stan/Analysis.hs
  src/Stan/Hie.hs
  stan.cabal
Labels: hie

#18 [#17] Create printing debugging functions for HieFile
  src/Stan.hs
  src/Stan/Hie/Debug.hs
  stan.cabal
Labels: hie

#19 [#16] Create core data types
  src/Stan/Core/Id.hs
  src/Stan/Hie/Debug.hs
  src/Stan/Inspection.hs
  src/Stan/Observation.hs
  stan.cabal
Labels: enhancement

#20 [#13] Count the number of analysed source code lines
  src/Stan/Analysis.hs
  src/Stan/Hie.hs
  stan.cabal
Labels: output, report :notebook:

#23 [#21] Add test on number of lines of code
  src/Stan.hs
  src/Stan/Analysis.hs
  src/Stan/Hie.hs
  stan.cabal
  test/Spec.hs
  test/Test/Analysis.hs
  test/Test/Example.hs
Labels: tests

#22 [#6] Check for usage of 'head' for lists
  src/Stan.hs
  src/Stan/Analysis.hs
  src/Stan/Analysis/Partial.hs
  src/Stan/Cli.hs
  src/Stan/Hie/Debug.hs
  src/Stan/Inspection.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Test/Analysis.hs
Labels: essential :bread:

#27 [#7] Create automatic test
  .github/workflows/ci.yml
  src/Stan/Core/Id.hs
  src/Stan/Observation.hs
  stan.cabal
  target/Target/Example.hs
  test/Spec.hs
  test/Test/Analysis.hs
  test/Test/Analysis/Partial.hs
  test/Test/Number.hs
Labels: tests

#28 [#8] Decide on the console output format
  src/Stan.hs
  src/Stan/Analysis/Partial.hs
  src/Stan/Analysis/Pretty.hs
  src/Stan/Inspection.hs
  src/Stan/Observation.hs
  stan.cabal
  target/Target/Example.hs
  test/Test/Analysis/Partial.hs
  test/Test/Number.hs
Labels: output

#42 [#25] Move 'Category' into separate module, introduce values, create list
  src/Stan/Category.hs
  src/Stan/Inspection.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Test/Number.hs
Labels: refactoring

#45 [#26] Smart constructors for 'Inspection' ids
  src/Stan/Analysis/Partial.hs
  src/Stan/Category.hs
  src/Stan/Inspection.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Spec.hs
  test/Test/Stan/Analysis.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Inspection.hs
  test/Test/Stan/Number.hs
Labels: enhancement, refactoring, tests

#48 [#47] Restructure Inspections and Analysis
  src/Stan/Analysis/Partial.hs
  src/Stan/Inspection.hs
  src/Stan/Inspection/All.hs
  src/Stan/Inspection/Partial.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Inspection.hs
  test/Test/Stan/Number.hs
Labels: refactoring

#49 [#40] Introduce 'Infinite' inspections
  src/Stan/Category.hs
  src/Stan/Inspection/All.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  stan.cabal
  test/Test/Stan/Inspection.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:

#50 [#38] Add some partial functions Inspections
  src/Stan/Analysis.hs
  src/Stan/Analysis/Analyser.hs
  src/Stan/Analysis/Partial.hs
  src/Stan/Inspection.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  src/Stan/NameMeta.hs
  stan.cabal
  target/Target/Example.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Inspection.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:

#51 [#30] Extend Severity data type
  src/Stan/Inspection.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  src/Stan/Observation.hs
  src/Stan/Severity.hs
  stan.cabal
  test/Test/Stan/Number.hs
Labels: enhancement

#52 [#40] Add checks for the 'Infinite' group
  src/Stan/Analysis.hs
  src/Stan/Analysis/Analyser.hs
  src/Stan/Analysis/Infinite.hs
  src/Stan/Analysis/Partial.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Observation.hs
  stan.cabal
  target/Target/Infinite.hs
  target/Target/Partial.hs
  test/Spec.hs
  test/Test/Stan/Analysis.hs
  test/Test/Stan/Analysis/Common.hs
  test/Test/Stan/Analysis/Infinite.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:, refactoring, tests

#54 [#53] Don't find identifier usages in imports
  src/Stan.hs
  src/Stan/Analysis/Analyser.hs
  test/Test/Stan/Analysis/Infinite.hs
Labels: enhancement

#56 [#34] Sort Observations by location
  src/Stan/Analysis/Pretty.hs
  src/Stan/Observation.hs
Labels: enhancement, output, report :notebook:

#57 [#43] Display the number of total checked inspections in the report
  src/Stan/Analysis/Pretty.hs
Labels: output, report :notebook:

#59 [#32] Stable ids for Observations
  src/Stan/Analysis/Analyser.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Spec.hs
  test/Test/Stan/Analysis/Common.hs
  test/Test/Stan/Analysis/Infinite.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Number.hs
  test/Test/Stan/Observation.hs
Labels: enhancement, refactoring

#60 [#31] Store inspections in 'HashMap'
  src/Stan/Analysis/Pretty.hs
  src/Stan/Core/Id.hs
  src/Stan/Inspection.hs
  src/Stan/Inspection/All.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  stan.cabal
  test/Test/Stan/Inspection.hs
Labels: enhancement, refactoring

#62 [#46] Add 'Stan.Core.ModuleName'
  src/Stan/Analysis/Analyser.hs
  src/Stan/Analysis/Pretty.hs
  src/Stan/Core/ModuleName.hs
  src/Stan/NameMeta.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Test/Stan/Analysis/Common.hs
  test/Test/Stan/Number.hs
Labels: refactoring

#63 [#34] Group observations into 'Slist'
  src/Stan/Analysis.hs
  src/Stan/Analysis/Analyser.hs
  src/Stan/Analysis/Pretty.hs
  src/Stan/Observation.hs
  stan.cabal
Labels: enhancement, library :books:, refactoring

#64 [#61] Simplify code structure for Inspection
  src/Stan/Analysis.hs
  src/Stan/Analysis/Analyser.hs
  src/Stan/Analysis/Infinite.hs
  src/Stan/Analysis/Partial.hs
  src/Stan/Inspection.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  stan.cabal
  test/Spec.hs
  test/Test/Stan/Analysis/Common.hs
  test/Test/Stan/Inspection.hs
  test/Test/Stan/Number.hs
  test/Test/Stan/Observation.hs
Labels: refactoring

#66 CLI command to show known Inspections
  src/Stan.hs
  src/Stan/Cli.hs
  src/Stan/Core/Id.hs
  src/Stan/Inspection.hs
  src/Stan/Inspection/All.hs
Labels: CLI, output

#67 [#38] Add inspections for '!!' and 'cycle'
  src/Stan/Inspection/Partial.hs
  target/Target/Partial.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:, tests

#68 [#38] Add 'genericIndex' partial inspection
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  src/Stan/NameMeta.hs
  stan.cabal
  target/Target/Partial.hs
  test/Test/Stan/Analysis/Common.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:, tests

#69 [#38] Add partial inspections for 'fromJust' and 'read'
  src/Stan/Inspection/Partial.hs
  target/Target/Partial.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:, tests

#71 [#33] Add --hide-solution option
  src/Stan.hs
  src/Stan/Analysis/Pretty.hs
  src/Stan/Cli.hs
  src/Stan/Core/Toggle.hs
  src/Stan/Observation.hs
  stan.cabal
  test/Test/Stan/Number.hs
Labels: CLI, output

#72 [#70] Create lenses for Inspection and NameMeta
  src/Stan/Category.hs
  src/Stan/Inspection.hs
  src/Stan/Inspection/Infinite.hs
  src/Stan/Inspection/Partial.hs
  src/Stan/NameMeta.hs
Labels: refactoring

#73 [#38] Add inspections for partial enumerable types
  src/Stan/Inspection/Partial.hs
  target/Target/Partial.hs
  test/Test/Stan/Analysis/Partial.hs
  test/Test/Stan/Number.hs
Labels: essential :bread:, tests

#77 [#14] Count the number of used unique language extensions
  app/Main.hs
  cabal.project
  src/Stan.hs
  src/Stan/Analysis.hs
  src/Stan/Analysis/Pretty.hs
  stan.cabal
  test/Test/Stan/Analysis.hs
Labels: analysis, enhancement

#79 [#75] Find filepath to cabal file
  src/Stan.hs
  src/Stan/Observation.hs
Labels: enhancement

#84 [#58] Implement type search in HIE files
  src/Stan/Analysis/Analyser.hs
  src/Stan/Cli.hs
  src/Stan/Hie/Match.hs
  src/Stan/NameMeta.hs
  stan.cabal
  test/Test/Stan/Number.hs
Labels: enhancement, hie
