Repository kowainik/stan, pull requests merged in 2020-08, with the labels that each got.

#369 [#368] Update 'unordered-containers' inspections
  CHANGELOG.md
  src/Stan/Inspection/AntiPattern.hs
  stack.yaml
Labels: fix, inspection

#367 Create dependabot.yml
  .github/dependabot.yml
Labels: CI, enhancement

#382 Update resolver to the latest LTS
  stack.yaml
Labels: CI
