Repository kowainik/stan, pull requests merged in 2020-07, with the labels that each got.

#334 [#323] Add a JSON output format
  CHANGELOG.md
  README.md
  src/Stan.hs
  src/Stan/Analysis.hs
  src/Stan/Cabal.hs
  src/Stan/Category.hs
  src/Stan/Cli.hs
  src/Stan/Core/Id.hs
  src/Stan/Core/ModuleName.hs
  src/Stan/FileInfo.hs
  src/Stan/Inspection.hs
  src/Stan/Observation.hs
  src/Stan/Severity.hs
  src/Stan/Toml.hs
  stack.yaml
  stan.cabal
  test/Test/Stan/Analysis.hs
Labels: enhancement

#340 Fix typo in Pretty.hs
  src/Stan/Analysis/Pretty.hs
Labels: documentation, fix

#344 [#335] Add srcSpan start/end col/line separately in JSON for Observation
  src/Stan/Analysis.hs
  src/Stan/Analysis/Pretty.hs
  src/Stan/Observation.hs
  src/Stan/Report/Html.hs
  test/Test/Stan/Analysis/Common.hs
Labels: output

#345 [#337] Implement binary releases on CI
  .github/workflows/ci.yml
  .github/workflows/release.yml
  CHANGELOG.md
  stan.cabal
Labels: CI

#349 [#338] Configure Stan installation for the Ubuntu
  README.md
Labels: CI, documentation

#353 [#55] Single-pass functions detection in Analysis
  CHANGELOG.md
  src/Stan/Analysis.hs
  src/Stan/Analysis/Analyser.hs
  src/Stan/Analysis/Visitor.hs
  stan.cabal
Labels: enhancement, performance 🏎️

#359 Fix --inspect-all argument typo in README.md
  README.md
Labels: documentation
